/** Public surface of this game, stable for embedding elsewhere: the <Map /> component plus the pure rules it's built on. */
export { default as Map } from "./Map.tsx";
export {
  CELL,
  MAZE,
  MAZE_COLS,
  MAZE_ROWS,
  NUM_GHOSTS,
  TELEPORTS,
  isWall,
  step,
  advance,
  tick,
  moveGhost,
  scatter,
  tilesOf,
  key,
  cleared,
  fruitOut,
  released,
  DOTS,
  FRUIT_AT,
  FRIGHT,
  FRUIT_SPAWN,
  FRUIT_TICKS,
  POINTS,
  LIVES,
  EXTRA_LIFE_AT,
  GHOST_HOUSE,
  GHOST_SPAWN,
  GHOSTS,
  TICK_MS,
  TURN_BUFFER,
  SPEED,
  NEW_GAME,
  PACMAN_SPAWN,
} from "./game/index.ts";
export type { CellCode, Dir, Game, Ghost, Tile } from "./game/index.ts";
